import type { Metadata } from 'next';
import './app.css';
import { StyledComponentsRegistry } from './registry';
import PrimerProvider from './components/PrimerProvider';
import Header from './components/Header';

export const metadata: Metadata = {
  title: 'Analytics',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <StyledComponentsRegistry>
          <Header />
          <PrimerProvider>{children}</PrimerProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
